accent = "#862020"
cursor = "#A85511"
foreground = "#D4D4D4"
background = "#121212"
selection_foreground = "#D4D4D4"
selection_background = "#A85511"

color0 = "#333333"
color1 = "#862020"
color2 = "#277D46"
color3 = "#A85511"
color4 = "#8B7F2E"
color5 = "#932A37"
color6 = "#2F8383"
color7 = "#bebebe"
color8 = "#8a8a8d"
color9 = "#C73838"
color10 = "#5BB775"
color11 = "#E07924"
color12 = "#C6B441"
color13 = "#C73838"
color14 = "#46BEBE"
color15 = "#eaeaea"
